name: Render Template
description: Renders file based on template and passed variables

author: step-security

branding:
  icon: file-text
  color: purple

inputs:
  template:
    description: Path to template
    required: true

  vars:
    description: Variables to use in template
    required: false

  vars_path:
    description: Path to YAML file with variables
    required: false

  result_path:
    description: Desired path to result file (optional)
    required: false

  timezone:
    description: Timezone to use in `date` template function
    required: false

outputs:
  result:
    description: Rendered file content

runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/render-template:v1.10.0@sha256:9c1fc91677928a9f3a4fe0a8eb1a218ca40be178e7c5a4871d754022a54b4c59' #v1.10.0
  
