name: main

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: "1.21"

      - name: Go Format
        run: gofmt -s -w -l $(find . -type f -name '*.go'| grep -v "/vendor/") && git diff --exit-code

      - name: Go Vet
        run: go vet ./...

      - name: Lint
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6.5.2
        with:
          version: latest

      - name: Test
        run: go test -v -count=1 -race -shuffle=on -coverprofile=coverage.txt -json ./... > test.json

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@2941118d7ef622b1b3771d1ff6eae9e90659eb26 # v0.8.0
        with:
          test-results: test.json

      - name: Test action
        uses: ./ # Uses an action in the root directory
        id: render
        with:
          template: ./testdata/template.txt
          vars: |
            name: world

      - name: Get `result` output
        run: echo "${{ steps.render.outputs.result }}"
